require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkoutTagsController do

  # This should return the minimal set of attributes required to create a valid
  # WorkoutTag. As you add validations to WorkoutTag, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all workout_tags as @workout_tags" do
      workout_tag = WorkoutTag.create! valid_attributes
      get :index
      assigns(:workout_tags).should eq([workout_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested workout_tag as @workout_tag" do
      workout_tag = WorkoutTag.create! valid_attributes
      get :show, :id => workout_tag.id.to_s
      assigns(:workout_tag).should eq(workout_tag)
    end
  end

  describe "GET new" do
    it "assigns a new workout_tag as @workout_tag" do
      get :new
      assigns(:workout_tag).should be_a_new(WorkoutTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested workout_tag as @workout_tag" do
      workout_tag = WorkoutTag.create! valid_attributes
      get :edit, :id => workout_tag.id.to_s
      assigns(:workout_tag).should eq(workout_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkoutTag" do
        expect {
          post :create, :workout_tag => valid_attributes
        }.to change(WorkoutTag, :count).by(1)
      end

      it "assigns a newly created workout_tag as @workout_tag" do
        post :create, :workout_tag => valid_attributes
        assigns(:workout_tag).should be_a(WorkoutTag)
        assigns(:workout_tag).should be_persisted
      end

      it "redirects to the created workout_tag" do
        post :create, :workout_tag => valid_attributes
        response.should redirect_to(WorkoutTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workout_tag as @workout_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutTag.any_instance.stub(:save).and_return(false)
        post :create, :workout_tag => {}
        assigns(:workout_tag).should be_a_new(WorkoutTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutTag.any_instance.stub(:save).and_return(false)
        post :create, :workout_tag => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workout_tag" do
        workout_tag = WorkoutTag.create! valid_attributes
        # Assuming there are no other workout_tags in the database, this
        # specifies that the WorkoutTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkoutTag.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => workout_tag.id, :workout_tag => {'these' => 'params'}
      end

      it "assigns the requested workout_tag as @workout_tag" do
        workout_tag = WorkoutTag.create! valid_attributes
        put :update, :id => workout_tag.id, :workout_tag => valid_attributes
        assigns(:workout_tag).should eq(workout_tag)
      end

      it "redirects to the workout_tag" do
        workout_tag = WorkoutTag.create! valid_attributes
        put :update, :id => workout_tag.id, :workout_tag => valid_attributes
        response.should redirect_to(workout_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the workout_tag as @workout_tag" do
        workout_tag = WorkoutTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutTag.any_instance.stub(:save).and_return(false)
        put :update, :id => workout_tag.id.to_s, :workout_tag => {}
        assigns(:workout_tag).should eq(workout_tag)
      end

      it "re-renders the 'edit' template" do
        workout_tag = WorkoutTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutTag.any_instance.stub(:save).and_return(false)
        put :update, :id => workout_tag.id.to_s, :workout_tag => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workout_tag" do
      workout_tag = WorkoutTag.create! valid_attributes
      expect {
        delete :destroy, :id => workout_tag.id.to_s
      }.to change(WorkoutTag, :count).by(-1)
    end

    it "redirects to the workout_tags list" do
      workout_tag = WorkoutTag.create! valid_attributes
      delete :destroy, :id => workout_tag.id.to_s
      response.should redirect_to(workout_tags_url)
    end
  end

end
